name: Build Danibot

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout source
        uses: actions/checkout@v3

      # Build project (for now just copy HTML into dist/)
      - name: Build project
        run: |
          mkdir -p dist
          cp Danibot.html dist/

      # Show contents of dist folder
      - name: Show build contents
        run: ls -l dist/

