name: Build Danibot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Run Jest tests
      - name: Run Jest tests
        run: npm test

      # Placeholder for Snyk security scan (enable after creating an account)
      - name: Snyk security scan
        if: false  # disabled until you add SNYK_TOKEN and want to run
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Build project
      - name: Build project
        run: |
          mkdir -p dist
          cp danibot.html dist/
          ls -l dist/

      # Show build contents
      - name: Show build contents
        run: ls -l dist/
